BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Controllers/urunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using stoktakip.Models.Entity;

namespace stoktakip.Controllers
{
    public class urunController : Controller
    {
        mvcstokEntities ra = new mvcstokEntities();

        // GET: urun
        public ActionResult Index()
        {
            var degerler = ra.urunler.ToList();
           
            return View(degerler);
        }
        [HttpGet]

        public ActionResult Urunekle()
        {
            return View();
        }
        [HttpPost]

        public ActionResult UrunEkle(urunler s1)
        {
            ra.urunler.Add(s1);
            ra.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var urun = ra.urunler.Find(id);
            ra.urunler.Remove(urun);
            ra.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urun = ra.urunler.Find(id);
            return View("UrunGetir", urun);
        }

        public ActionResult Güncelle(urunler p1)
        {
            var urun = ra.urunler.Find(p1.urun_id);
            urun.urun_id = p1.urun_id;
            urun.urun_ad = p1.urun_ad;
            urun.urun_kategori = p1.urun_kategori;
            urun.fiyat = p1.fiyat;
            urun.marka = p1.marka;
            urun.stok = p1.stok;
            return RedirectToAction("Index");

        }
    }
}

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/urun/Index.cshtml
@using stoktakip.Models.Entity

@model List<urunler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style=" width:1139px; height:100px;  background-image: url('../../images/banner.png');">

</div>
<table class="table table-striped text-center bg-danger">
    <thead class="bg-primary">
        <th class="text-center">ÜRÜN ID</th>
        <th class="text-center" >ÜRÜN AD</th>
        <th  class="text-center">ÜRÜN KATEGORİSİ</th>
        <th class="text-center">ÜRÜN FİYATI</th>
        <th class="text-center">MARKA</th>
        <th class="text-center">STOK</th>
        <th class="text-center">SİL</th>
        <th class="text-center">GÜNCELLE</th>
    </thead>
    <tbody>
        @foreach(var urn in Model)
            {
        <tr>
            <td>@urn.urun_id</td>
            <td>@urn.urun_ad</td>
            <td>@urn.urun_kategori</td>
            <td>@urn.fiyat</td>
            <td>@urn.marka</td>
            <td>@urn.stok</td>
            <td><a href="/Urun/Sil/@urn.urun_id" class="btn btn-danger">SİL</a> </td>
            <td><a href ="/Urun/UrunGetir/@urn.urun_id"class="btn btn-success">GÜNCELLE</a></td>
        </tr>
            }
    </tbody>
</table>
<a href="/urun/UrunEkle"class=" btn btn-primary"> Yeni Ürün Ekle</a>

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/urun/UrunEkle.cshtml
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style=" width:1139px; height:85px;  background-image: url('../../images/depo.png');">

</div><br />


<form class="form-group" method="post">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="urun_ad" required="" />
    </div>

    <div>
        <label>Kategori Seçiniz</label>
        <input type="text" class="form-control" name="urun_kategori" required="" />
    </div>

    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="fiyat" required="" />
    </div>

    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="marka" required="" />
    </div>

    <div>
        <label>Stok Adet</label>
        <input type="text" class="form-control" name="stok" required="" />
        <br />
    </div>

    <button class="btn btn-info">Ürün Ekle</button>
</form>

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/urun/UrunGetir.cshtml
@model stoktakip.Models.Entity.urunler

@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style="background-repeat:no-repeat; width: 1000px; height: 100px; background-image: url('../../images/updates.png');">

</div>
<br />

@using (Html.BeginForm("Güncelle", "urun", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(k => k.urun_id, "Ürün ID")
        @Html.TextBoxFor(k => k.urun_id, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.urun_ad, "Ürün Ad")
        @Html.TextBoxFor(k => k.urun_ad, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.urun_kategori, "Ürün Kategori")
        @Html.TextBoxFor(k => k.urun_kategori, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.fiyat, "Fiyat")
        @Html.TextBoxFor(k => k.fiyat, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.marka, "Marka")
        @Html.TextBoxFor(k => k.marka, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.stok, "Stok")
        @Html.TextBoxFor(k => k.stok, new { @class = "form-control" })
        <br />

        <div>

            <button class="btn btn-warning">ÜRÜN GÜNCELLE</button>

        </div>

    </div>
}