BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Controllers/ketegoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using stoktakip.Models.Entity;

namespace stoktakip.Controllers
{
    public class ketegoriController : Controller
    {
        mvcstokEntities db = new mvcstokEntities();

        public ActionResult Index()
        {
            var degerler = db.kategoriler.ToList();
            return View(degerler);
        }
        [HttpGet]

        public ActionResult Yenikategori()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Yenikategori(kategoriler p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }
            db.kategoriler.Add(p1);
            db.SaveChanges();
            return View();


        }

        public ActionResult Sil(int id)
        {
            var kategori =db.kategoriler.Find(id);
            db.kategoriler.Remove(kategori);
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.kategoriler.Find(id);
            return View("KategoriGetir", ktgr);
        }

        public ActionResult Güncelle(kategoriler p1)
        {
            var ktgr = db.kategoriler.Find(p1.kategori_id);
            ktgr.kategori_id = p1.kategori_id;
            ktgr.kategori_ad = p1.kategori_ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/ketegori/Index.cshtml
@using stoktakip.Models.Entity

@model List<kategoriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style=" width:1139px; height:100px;  background-image: url('../../images/banner.png');">

</div>

<table class="table table-striped text-center bg-danger">
    <thead class="bg-primary">
        <th class="text-center">KATEGORİ ID</th>
        <th class="text-center">KATEGORİ AD</th>
        <th class="text-center">SİL</th>
        <th class="text-center">GÜNCELLE</th>
    </thead>
    <tbody>
        @foreach (var ktgr in Model)
        {
            <tr>
                <td>@ktgr.kategori_id</td>
                <td>@ktgr.kategori_ad</td>
                <td><a href="/ketegori/Sil/@ktgr.kategori_id" class="btn btn-danger">SİL</a> </td>
                <td><a href="/ketegori/KategoriGetir/@ktgr.kategori_id" class="btn btn-success">GÜNCELLE</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/ketegori/Yenikategori" class=" btn btn-primary"> Yeni Kategori Ekle</a>

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/ketegori/KategoriGetir.cshtml
@model stoktakip.Models.Entity.kategoriler

@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style="background-repeat:no-repeat; width: 1000px; height: 100px; background-image: url('../../images/updates.png');">

</div>
<br />

@using (Html.BeginForm("Güncelle", "ketegori", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(k => k.kategori_id, "Ketegori ID")
        @Html.TextBoxFor(k => k.kategori_id, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.kategori_ad, "Kategori Ad")
        @Html.TextBoxFor(k => k.kategori_ad, new { @class = "form-control" })
        <br />
        <div> <button class="btn btn-warning">KATEGORİ GÜNCELLE</button></div>
    </div>
}

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/ketegori/Yenikategori.cshtml
@{
    ViewBag.Title = "Yenikategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style=" width: 1139px; height: 85px; background-image: url('../../images/kategori-ekle.png');">

</div>
<form class="form-group" method="post">
    <div>
        <label>Kategori Adı</label>
        <input type="text" class="form-control" name="kategori_ad" required="" />
    </div><br />
    <button class="btn btn-info">Kategori Ekle</button>
</form>