BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Controllers/musteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using stoktakip.Models.Entity;

namespace stoktakip.Controllers
{
    public class musteriController : Controller
    {
        mvcstokEntities db = new mvcstokEntities();
        // GET: müsteri
        public ActionResult Index()
        {
            var degerler = db.musteriler.ToList();
            return View(degerler);
        }

        [HttpGet]

        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]

        public ActionResult YeniMusteri(musteriler p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.musteriler.Add(p1);
            db.SaveChanges();
            return View();
        }


        public ActionResult Sil(int id)
        {
            var musteri = db.musteriler.Find(id);
            db.musteriler.Remove(musteri);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    
        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.musteriler.Find(id);
            return View("MusteriGetir", musteri);
        }

        public ActionResult Güncelle(musteriler p1)
        {
            var musteri = db.musteriler.Find(p1.musteri_id);
            musteri.musteri_id = p1.musteri_id;
            musteri.musteri_ad = p1.musteri_ad;
            musteri.musteri_soyad = p1.musteri_soyad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/musteri/Index.cshtml
@using stoktakip.Models.Entity

@model List<musteriler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style=" width:1139px; height:100px;  background-image: url('../../images/banner.png');">

</div>

<table class="table table-striped text-center bg-danger">
    <thead class="bg-primary">
        <th class="text-center">MÜŞTERİ ID</th>
        <th class="text-center">MÜŞTERİ AD</th>
        <th class="text-center">MÜŞTERİ SOYAD</th>
        <th class="text-center">SİL</th>
        <th class="text-center">GÜNCELLE</th>
    </thead>
    <tbody>
        @foreach (var mstr in Model)
        {
            <tr style="">
                <td>@mstr.musteri_id</td>
                <td>@mstr.musteri_ad</td>
                <td>@mstr.musteri_soyad</td>
                <td><a href="/musteri/Sil/@mstr.musteri_id" class="btn btn-danger">SİL</a> </td>
                <td><a href="/musteri/MusteriGetir/@mstr.musteri_id" class="btn btn-success">GÜNCELLE</a></td>


            </tr>
        }
    </tbody>
</table>
<a href="/musteri/YeniMusteri" class=" btn btn-primary"> Yeni Müşteri Ekle</a>

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/musteri/MusteriGetir.cshtml
@model stoktakip.Models.Entity.musteriler

@{
    ViewBag.Title = "Güncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style="background-repeat:no-repeat; width: 1000px; height: 100px; background-image: url('../../images/updates.png');">

</div>
<br />
@using (Html.BeginForm("Güncelle", "musteri", FormMethod.Post))
{
    <div class="form-group">

        @Html.LabelFor(k => k.musteri_id, "Müşteri ID")
        @Html.TextBoxFor(k => k.musteri_id, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.musteri_ad, "Müşteri Ad")
        @Html.TextBoxFor(k => k.musteri_ad, new { @class = "form-control" })<br />

        @Html.LabelFor(k => k.musteri_soyad, "Müşteri Soyad")
        @Html.TextBoxFor(k => k.musteri_soyad, new { @class = "form-control" })
        <br />
        <div>

            <button class="btn btn-warning">MÜŞTERİ GÜNCELLE</button>

        </div>

    </div>
}

BLM226 - Nesneye Dayalı Programlama/stoktakip/stoktakip/Views/musteri/YeniMusteri.cshtml
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style=" width: 1139px; height: 85px; background-image: url('../../images/costumer.png');">

</div><br />
<form class="form-group" method="post">
    <div>
        <label>Müşteri Adı</label>
        <input type="text" class="form-control" name="musteri_ad" required="" />
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="musteri_soyad" required="" />
    </div><br />
    <button class="btn btn-info">Müşteri Ekle</button>
</form>